# Configurations
title:            Textbook of Life
longtitle:        The Textbook of Life
author:           Mitchell Starrenburg
# email:            sighingnow@gmail.com
description: fff

version:          1.0
gitbook_version:  3.2.3

url:              'https://mstarren.github.io'
# baseurl:          '/jekyll-gitbook'
# rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/
  Book1-TheGoodLife:
    output: true
    #permalink: /:collection/:path/
  Book2-TheVirtuousLife:
    output: true
    #permalink: /:collection/:path/
  Book3-TheWiseLife:
    output: true
    #permalink: /:collection/:path/
  Book4-TheSkilledLife:
    output: true
    #permalink: /:collection/:path/

ordered_collections:
  - posts
  - Book1-TheGoodLife
  - Book2-TheVirtuousLife
  - Book3-TheWiseLife
  - Book4-TheSkilledLife
  - pages
  - others

page_width: 1000px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
